server:
  port: 8202

spring:
  application:
    name: Lapland-Server-Test
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8001

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user
