server:
  port: 8101

spring:
  application:
    name: Lapland-Auth
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8001

#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 20
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    instance-info-replication-interval-seconds: 30
#    registry-fetch-interval-seconds: 3
#    serviceUrl:
#      defaultZone: http://meiyu:123456@localhost:8001/register/eureka/
